Vagrant.configure(2) do |config|
  config.vm.box = "psoratc8amq"
  config.vm.box_url = "https://artifactory.psdevelop.com/artifactory/api/vagrant/PS-VagrantBoxes/psoratc8amq"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.name="${rootArtifactId}-${version}"
    end
end
